iptables block network access until sdwdate succeeded
enable Whonix-Workstation firewall by default

removed feature to keep Whonix-Workstation firewall easily disabled by default
(can still be done by a /etc/whonix_firewall.d config snippet 'exit 0')

https://phabricator.whonix.org/T533

diff --git a/usr/bin/whonix_firewall b/usr/bin/whonix_firewall
--- a/usr/bin/whonix_firewall
+++ b/usr/bin/whonix_firewall
@@ -76,6 +76,7 @@ variables_defaults() {
 
    [ -n "$TUNNEL_USER" ] || TUNNEL_USER="$(id -u tunnel)"
    [ -n "$SDWDATE_USER" ] || SDWDATE_USER="$(id -u sdwdate)" || true
+   [ -n "$WHONIXCHECK_USER" ] || WHONIXCHECK_USER="$(id -u whonixcheck)" || true
 
    ## Control Port Filter Proxy Port
    [ -n "$CONTROL_PORT_FILTER_PROXY_PORT" ] || CONTROL_PORT_FILTER_PROXY_PORT="9052"
@@ -134,32 +135,6 @@ variables_defaults() {
    fi
 }
 
-run_or_not() {
-   if [ "$WORKSTATION_FIREWALL" = "1" ] || [ "$TUNNEL_FIREWALL_ENABLE" = "true" ]; then
-      true
-   else
-      set -x
-      : " "
-      : " "
-      : "#################################################"
-      : "## Whonix second, optional, extra firewall INFO #"
-      : "#################################################"
-      : "##"
-      : "## There is a second, extra firewall for Whonix-Workstation."
-      : "## It is disabled by default."
-      : "## Experts should read the design notes in"
-      : "## its man page and make an informed decision."
-      : "##    man whonix_firewall"
-      : "##"
-      : "########################################################"
-      : "## End of Whonix second, optional, extra firewall INFO #"
-      : "########################################################"
-      : " "
-      exit 0
-   fi
-}
-
-
 ipv4_defaults() {
    ## Set secure defaults.
    $iptables_cmd -P INPUT DROP
@@ -199,6 +174,12 @@ ipv4_drop_invalid_incoming_packages() {
 
    ## DROP INCOMING MALFORMED NULL PACKETS
    $iptables_cmd -A INPUT -p tcp --tcp-flags ALL NONE -j DROP
+}
+
+qubes() {
+   ## Not yet required. Just so Whonix-Workstation firewall can be more similar
+   ## to Whonix-Gateway firewall.
+   true
 }
 
 ipv4_input_rules() {
@@ -265,47 +246,74 @@ ipv4_reject_invalid_outgoing_packages() {
 }
 
 ipv4_output() {
-   ## Allow unlimited traffic on localhost.
-   $iptables_cmd -A OUTPUT -o lo -j ACCEPT
+   if [ "$firewall_mode" = "timesync-fail-closed" ]; then
+      true "firewall_mode is $firewall_mode, therefore not allowing all localhost traffic."
+   else
+      true "firewall_mode is $firewall_mode, therefore allowing all localhost traffic."
+      ## Allow unlimited traffic on localhost.
+      $iptables_cmd -A OUTPUT -o lo -j ACCEPT
+   fi
 
    ## Allow outgoing traffic on VPN interface,
    ## if TUNNEL_FIREWALL_ENABLE mode is enabled.
    ## DISABLED BY DEFAULT.
    if [ "$TUNNEL_FIREWALL_ENABLE" = "true" ]; then
-      $iptables_cmd -A OUTPUT -o "$VPN_INTERFACE" -j ACCEPT
-
-      ## Connections to VPN servers are allowed,
-      $iptables_cmd -A OUTPUT -m owner --uid-owner "$TUNNEL_USER" -j ACCEPT
+      if [ "$firewall_mode" = "timesync-fail-closed" ]; then
+         true "firewall_mode is $firewall_mode, therefore not allowing user $TUNNEL_USER traffic."
+      else
+         true "firewall_mode is $firewall_mode, therefore allowing user $TUNNEL_USER traffic."
+         ## Connections to VPN servers are allowed,
+         $iptables_cmd -A OUTPUT -o "$VPN_INTERFACE" -j ACCEPT
+         $iptables_cmd -A OUTPUT -m owner --uid-owner "$TUNNEL_USER" -j ACCEPT
+      fi
 
       if [ "$TUNNEL_FIREWALL_ALLOW_SDWDATE_USER" = "true" ]; then
-         $iptables_cmd -A OUTPUT -m owner --uid-owner "$SDWDATE_USER" -j ACCEPT || true
+         $iptables_cmd -A OUTPUT -m owner --uid-owner "$SDWDATE_USER" -m iprange --dst-range "127.0.0.1" -j ACCEPT
+         $iptables_cmd -A OUTPUT -m owner --uid-owner "$SDWDATE_USER" -m iprange --dst-range "$GATEWAY_IP" -j ACCEPT
       fi
 
       ## Accept outgoing connections to local network.
       if [ "$TUNNEL_FIREWALL_ALLOW_LOCAL_NET" = "true" ]; then
-         for NET in $LOCAL_NET; do
-            $iptables_cmd -A OUTPUT -m iprange --dst-range "$NET" -j ACCEPT
-         done
+         if [ "$firewall_mode" = "timesync-fail-closed" ]; then
+            true
+         else
+            for NET in $LOCAL_NET; do
+               $iptables_cmd -A OUTPUT -m iprange --dst-range "$NET" -j ACCEPT
+            done
+         fi
       fi
 
       if [ "$TUNNEL_FIREWALL_ALLOW_CONTROL_PORT_FILTER_PROXY" = "true" ]; then
+         $iptables_cmd -A OUTPUT -p tcp --dport "$CONTROL_PORT_FILTER_PROXY_PORT" --dst "127.0.0.1" -j ACCEPT
          $iptables_cmd -A OUTPUT -p tcp --dport "$CONTROL_PORT_FILTER_PROXY_PORT" --dst "$GATEWAY_IP" -j ACCEPT
       fi
 
       if [ "$TUNNEL_FIREWALL_ALLOW_TB_UPDATER" = "true" ]; then
-         for socks_port in $SOCKS_PORT_TBB_DOWNLOAD $SOCKS_PORT_TBB_GPG ; do
-            $iptables_cmd -A OUTPUT -p tcp --dport "$socks_port" --dst "$GATEWAY_IP" -j ACCEPT
-         done
+         if [ "$firewall_mode" = "timesync-fail-closed" ]; then
+            true
+         else
+            for socks_port in $SOCKS_PORT_TBB_DOWNLOAD $SOCKS_PORT_TBB_GPG ; do
+               $iptables_cmd -A OUTPUT -p tcp --dport "$socks_port" --dst "$GATEWAY_IP" -j ACCEPT
+            done
+         fi
       fi
 
       if [ "$TUNNEL_FIREWALL_ALLOW_WHONIXCHECK" = "true" ]; then
-         for socks_port in $SOCKS_PORT_WHONIXCHECK $SOCKS_PORT_WHONIX_NEWS ; do
-            $iptables_cmd -A OUTPUT -p tcp --dport "$socks_port" --dst "$GATEWAY_IP" -j ACCEPT
-         done
+         if [ "$firewall_mode" = "timesync-fail-closed" ]; then
+            true
+         else
+            $iptables_cmd -A OUTPUT -m owner --uid-owner "$WHONIXCHECK_USER" -m iprange --dst-range "127.0.0.1" -j ACCEPT
+            $iptables_cmd -A OUTPUT -m owner --uid-owner "$WHONIXCHECK_USER" -m iprange --dst-range "$GATEWAY_IP" -j ACCEPT
+         fi
       fi
    else
-      ## Allow Whonix-Workstation to query Whonix-Gateway for DNS.
-      $iptables_cmd -A OUTPUT -p udp --dport 53 --dst "$GATEWAY_IP" -j ACCEPT
+      if [ "$firewall_mode" = "timesync-fail-closed" ]; then
+         true "firewall_mode is $firewall_mode, therefore not allowing DNS traffic."
+      else
+         true "firewall_mode is $firewall_mode, therefore allowing DNS traffic."
+         ## Allow Whonix-Workstation to query Whonix-Gateway for DNS.
+         $iptables_cmd -A OUTPUT -p udp --dport 53 --dst "$GATEWAY_IP" -j ACCEPT
+      fi
 
       ## Not sure about the next one. UDP is not supported by Tor, why not
       ## block any outgoing UDP. Might have unwanted side effects when tunneling
@@ -326,8 +334,24 @@ ipv4_output() {
       ## The next rule ensures, that only tcp can leave and achieves the desired result from (2).
       $iptables_cmd -A OUTPUT ! -p tcp -j REJECT --reject-with icmp-port-unreachable
 
-      ## Allow full outgoing connection but no incoming stuff.
-      $iptables_cmd -A OUTPUT -j ACCEPT
+      if [ "$firewall_mode" = "timesync-fail-closed" ]; then
+         true "firewall_mode is $firewall_mode, therefore not allowing all outgoing traffic."
+
+         ## Allow sdwdate talking to localhost and Tor in Whonix firewall timesync-fail-closed mode.
+         ## Otherwise in Whonix firewall full mode this rule is redundant.
+         $iptables_cmd -A OUTPUT -m owner --uid-owner "$SDWDATE_USER" -m iprange --dst-range "127.0.0.1" -j ACCEPT
+         $iptables_cmd -A OUTPUT -m owner --uid-owner "$SDWDATE_USER" -m iprange --dst-range "$GATEWAY_IP" -j ACCEPT
+
+         $iptables_cmd -A OUTPUT -m owner --uid-owner "$WHONIXCHECK_USER" -m iprange --dst-range "127.0.0.1" -j ACCEPT
+         $iptables_cmd -A OUTPUT -m owner --uid-owner "$WHONIXCHECK_USER" -m iprange --dst-range "$GATEWAY_IP" -j ACCEPT
+
+         $iptables_cmd -A OUTPUT -p tcp --dport "$CONTROL_PORT_FILTER_PROXY_PORT" --dst "127.0.0.1" -j ACCEPT
+         $iptables_cmd -A OUTPUT -p tcp --dport "$CONTROL_PORT_FILTER_PROXY_PORT" --dst "$GATEWAY_IP" -j ACCEPT
+      else
+         true "firewall_mode is $firewall_mode, therefore allowing all outgoing traffic."
+         ## Allow full outgoing connection but no incoming stuff.
+         $iptables_cmd -A OUTPUT -j ACCEPT
+      fi
 
       ## Log.
       #$iptables_cmd -A OUTPUT -j LOG --log-prefix "Whonix blocked output4: "
@@ -428,13 +452,9 @@ main() {
    init
    firewall_mode_detection
    variables_defaults
-
-   run_or_not
-
    ipv4_defaults
    ipv4_preparation
    ipv4_drop_invalid_incoming_packages
-   #qubes
    ipv4_input_rules
    ipv4_input_defaults
    ipv4_forward
